repos:
  # Essential file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format (vendored)
        entry: ruff format
        language: system
        types_or: [python, pyi, jupyter]

      - id: ruff-fix
        name: ruff-fix
        entry: ruff check
        args: [--fix, --exit-zero]
        language: system
        types_or: [python, pyi, jupyter]
